//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTTQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INPUT_INFOR
    {
        public int INPUT_INFOR_ID { get; set; }
        public Nullable<int> INPUT_ID { get; set; }
        public Nullable<int> ACCOUNT_ID { get; set; }
        public string TYPE_INPUT { get; set; }
        public string PERIODIC { get; set; }
        public Nullable<double> AMOUNT_MONEY { get; set; }
        public string UNIT_MONEY { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual INPUT INPUT { get; set; }
    }
}
