//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTTQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INPUT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INPUT()
        {
            this.INPUT_INFOR = new HashSet<INPUT_INFOR>();
        }
    
        public int INPUT_ID { get; set; }
        public Nullable<System.DateTime> DATE_INPUT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INPUT_INFOR> INPUT_INFOR { get; set; }
    }
}
