//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTTQ.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUAN_LY_CHI_TIEUEntities : DbContext
    {
        public QUAN_LY_CHI_TIEUEntities()
            : base("name=QUAN_LY_CHI_TIEUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<INPUT> INPUTs { get; set; }
        public virtual DbSet<INPUT_INFOR> INPUT_INFOR { get; set; }
        public virtual DbSet<OUTPUT> OUTPUTs { get; set; }
        public virtual DbSet<OUTPUT_INFOR> OUTPUT_INFOR { get; set; }
        public virtual DbSet<USER_> USER_ { get; set; }
    }
}
