//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTTQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTPUT_INFOR
    {
        public int OUTPUT_INFOR_ID { get; set; }
        public Nullable<int> OUTPUT_ID { get; set; }
        public Nullable<int> ACCOUNT_ID { get; set; }
        public string TYPE_OUTPUT { get; set; }
        public string PAY { get; set; }
        public Nullable<double> AMOUNT_MONEY { get; set; }
        public string UNIT_MONEY { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual OUTPUT OUTPUT { get; set; }
    }
}
